{
  "language": "python",
  "os": [
    "linux"
  ],
  "dist": "xenial",
  "python": [
    "3.9.4"
  ],
  "install": [
    "pip install -r requirements.txt"
  ],
  "script": [
    "echo overide build"
  ]
}
